name: Check, Build, and Test New Version Artifacts

on: push

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8 for AVD Manager
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Run AVD Manager
        run: echo "y" | $ANDROID_HOME/tools/bin/avdmanager list avd

      # If you need Java 11 (or another version) for subsequent steps, you can switch back like this:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Install necessary system dependencies for the Android Emulator
      - name: Install system dependencies
        run: sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null

      - name: Set up KVM
        run: sudo apt-get install -y qemu-kvm > /dev/null

      # Setup Android environment
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # List available AVDs
      - name: List AVDs
        run: echo "y" | $ANDROID_HOME/tools/bin/avdmanager list avd

      # Create and launch emulator
      - name: Create and launch emulator
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test -k "system-images;android-29;default;x86_64"
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'


      - name: Extract Version Code
        run: echo "VersionCode=$(grep 'vCode' app/version.properties | grep -o '[0-9]*')" >> $GITHUB_ENV

      - name: Fetch Git Tags
        run: git fetch --tags

      - name: Count Git Tags
        id: count_tags
        run: echo "tag_count=$(git tag | wc -l)" >> $GITHUB_ENV

      - name: Check for New Version
        id: check_version
        run: |
          if [ "${{ env.tag_count }}" -gt $VersionCode ]; then
            echo "New version available!"
            echo "New version code: ${{ env.tag_count }}"
            echo "new_version=true" >> $GITHUB_ENV
          else
            echo "No new version available."
            echo "new_version=false" >> $GITHUB_ENV
          fi

      - name: Build All Variants
#        if: env.new_version == 'true'
        run: ./gradlew assemble

      - name: Run Instrumented Tests
        run: ./gradlew connectedCheck

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/

      - name: List All Build Outputs
        run: ls -R app/build/outputs/

      - name: List APK Directory Contents
        run: ls -R app/build/outputs/apk/

      - name: Upload recyclerStandard Debug APK
#        if: env.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerStandard-debug.apk
          path: app/build/outputs/apk/recyclerStandard/debug/app-recyclerStandard-debug.apk

      - name: Upload recyclerStandard Release APK
#        if: env.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerStandard-release.apk
          path: app/build/outputs/apk/recyclerStandard/release/app-recyclerStandard-release.apk

      - name: Upload recyclerPro Debug APK
#        if: env.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerPro-debug.apk
          path: app/build/outputs/apk/recyclerPro/debug/app-recyclerPro-debug.apk

      - name: Upload recyclerPro Release APK
#        if: env.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerPro-release.apk
          path: app/build/outputs/apk/recyclerPro/release/app-recyclerPro-release.apk



