name: Check and Build New Version Artifacts

on: push

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Version Code
        run: echo "VersionCode=$(grep 'vCode' app/version.properties | grep -o '[0-9]*')" >> $GITHUB_ENV

      - name: Fetch Git Tags
        run: git fetch --tags

      - name: Count Git Tags
        id: count_tags
        run: echo "::set-output name=tag_count::$(git tag | wc -l)"

      - name: Check for New Version
        id: check_version
        run: |
          if [ "${{ steps.count_tags.outputs.tag_count }}" -gt VersionCode ]; then
            echo "New version available!"
            echo "New version code: ${{ steps.count_tags.outputs.tag_count }}"
            echo "::set-output name=new_version::true"
          else
            echo "No new version available."
            echo "::set-output name=new_version::false"
          fi

      - name: Create New Version
        if: steps.check_version.outputs.new_version == 'true'
        run: ./gradlew assembleDebug  # Replace with your build command

      - name: Upload Full Debug Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app-full-debug.apk
          path: app/full/debug/app-full-debug.apk
