name: Check and Build New Version Artifacts

on: push

jobs:
  check_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version Code
        run: echo "VersionCode=$(grep 'vCode' app/version.properties | grep -o '[0-9]*')" >> $GITHUB_ENV

      - name: Fetch Git Tags
        run: git fetch --tags

      - name: Count Git Tags
        id: count_tags
        run: echo "tag_count=$(git tag | wc -l)" >> $GITHUB_ENV

      - name: Check for New Version
        id: check_version
        run: |
          if [ "${{ steps.count_tags.outputs.tag_count }}" -gt $VersionCode ]; then
            echo "New version available!"
            echo "New version code: ${{ steps.count_tags.outputs.tag_count }}"
            echo "::set-output name=new_version::true"
          else
            echo "No new version available."
            echo "::set-output name=new_version::false"
          fi

      - name: Build All Variants
        if: steps.check_version.outputs.new_version == 'true'
        run: ./gradlew assemble

      - name: Upload recyclerStandard Debug APK
        if: steps.check_version.outputs.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerStandard-debug.apk
          path: app/build/outputs/apk/recyclerStandard/debug/app-recyclerStandard-debug.apk

      - name: Upload recyclerStandard Release APK
        if: steps.check_version.outputs.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerStandard-release.apk
          path: app/build/outputs/apk/recyclerStandard/release/app-recyclerStandard-release.apk

      - name: Upload recyclerPro Debug APK
        if: steps.check_version.outputs.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerPro-debug.apk
          path: app/build/outputs/apk/recyclerPro/debug/app-recyclerPro-debug.apk

      - name: Upload recyclerPro Release APK
        if: steps.check_version.outputs.new_version == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: recyclerPro-release.apk
          path: app/build/outputs/apk/recyclerPro/release/app-recyclerPro-release.apk
